SELECT * FROM car_model.sales;
use car_model;
select * from sales;
-- Display car model names and their prices

SELECT model_name, prize FROM model;

-- Find all petrol cars with price greater than 12,00,000

SELECT * 
FROM model
WHERE fuel_type = 'Petrol' AND prize > 1200000;

-- List all unique fuel types available in the showroom

SELECT DISTINCT fuel_type FROM model;

-- Display car model names and prices with custom column names

SELECT model_name AS Car_Model,
       prize AS Prize
FROM model;

-- Find top 3 most expensive cars

SELECT * 
FROM model
ORDER BY prize DESC
LIMIT 3;

-- Find top 3 cheapest cars
SELECT * 
FROM model
ORDER BY prize asc
LIMIT 3;

-- Find all customers who live in Mumbai
SELECT * 
FROM customer
WHERE city = 'Mumbai';

-- Show latest 5 launched car models

select * from model order by launch_year desc limit 5;

-- Count number of cars sold by each dealership

select deal_id, count(*) as total_cars_sold
from sales
group by deal_id;


select deal_id, count(*) as total_cars_sold
from sales
group by deal_id;

-- Calculate total revenue generated by each car model

SELECT 
    m.MODEL_NAME,
    SUM(s.selling_price) AS TOTAL_REVENUE
FROM sales s
JOIN MODEL m
    ON s.car_id = m.CAR_ID
GROUP BY m.MODEL_NAME;

-- ind customers who bought more than 1 car

SELECT c.cus_name, COUNT(*) AS purchases
FROM sales s
JOIN customer c ON s.customer_id = c.customer_id
GROUP BY c.cus_name
HAVING COUNT(*) > 1;

-- Find total revenue generated by each dealership

SELECT d.deal_name, SUM(s.selling_price) AS revenue
FROM sales s
JOIN dealership d ON s.deal_id = d.deal_id
GROUP BY d.deal_name;

-- Find most sold car model

SELECT m.model_name, COUNT(*) AS total_sold
FROM sales s
JOIN model m ON s.car_id = m.car_id
GROUP BY m.model_name
ORDER BY total_sold DESC
LIMIT 1;

--  Find customers who bought electric cars

SELECT DISTINCT c.cus_name
FROM sales s
JOIN customer c ON s.customer_id = c.customer_id
JOIN model m ON s.car_id = m.car_id
WHERE m.fuel_type = 'ELECTRIC';


-- Find dealership with highest sales count

SELECT d.deal_name, COUNT(*) AS total_sales
FROM sales s
JOIN dealership d ON s.deal_id = d.deal_id
GROUP BY d.deal_name
ORDER BY total_sales DESC
LIMIT 1;

-- Find total revenue per fuel type

SELECT m.fuel_type, SUM(s.selling_price) AS revenue
FROM sales s
JOIN model m ON s.car_id = m.car_id
GROUP BY m.fuel_type;

-- Find second highest selling price

SELECT DISTINCT selling_price
FROM sales
ORDER BY selling_price DESC
LIMIT 1 OFFSET 1;

-- Find customers who never purchased a car

SELECT c.cus_name
FROM customer c
LEFT JOIN sales s ON c.customer_id = s.customer_id
WHERE s.customer_id IS NULL;

-- Find most profitable car model (highest revenue)

SELECT m.model_name, SUM(s.selling_price) AS revenue
FROM sales s
JOIN model m ON s.car_id = m.car_id
GROUP BY m.model_name
ORDER BY revenue DESC
LIMIT 1;

-- Find monthly sales report

SELECT MONTH(sale_date) AS month, COUNT(*) AS total_sales
FROM sales
GROUP BY MONTH(sale_date);

-- Find dealership that sold all types of fuel cars
select * from dealership;

select deal_name from dealership;
SELECT d.deal_name
FROM dealership d
JOIN sales s ON d.deal_id = s.deal_id
JOIN model m ON s.car_id = m.car_id
GROUP BY d.deal_name
HAVING COUNT(DISTINCT UPPER(m.fuel_type)) = 
       (SELECT COUNT(DISTINCT UPPER(fuel_type)) FROM model);
       
-- Create a VIEW for sales summary

SELECT c.cus_name, m.model_name, d.deal_name, s.selling_price
FROM sales s
JOIN customer c ON s.customer_id = c.customer_id
JOIN model m ON s.car_id = m.car_id
JOIN dealership d ON s.deal_id = d.deal_id;